ARM: dts: ux500: samsung-golden: Add magnetometer
novathor-mainline/linux pull request #2
Opened 2020-01-25 16:14 UTC by AffeAli

While writing a driver for the magnetometer I noticed that the ak8974 driver is compatible with it.
A mount-matix may be required.(I don't know how to get this information)

2020-01-25 19:11 UTC, stephan-gh requested changes
Thanks again for the patches and especially for finding the similarity with ak8974!  
It seems to be working fine for me.

I compared the registers used by the mainline driver with the one listed in the Alps datasheet. They are almost identical, but there are some subtle differences that we should handle in the mainline driver. I tried to mark them inline:

```diff
diff --git a/drivers/iio/magnetometer/ak8974.c b/drivers/iio/magnetometer/ak8974.c
index e2b31e9d4b35..12fdf10eb916 100644
--- a/drivers/iio/magnetometer/ak8974.c
+++ b/drivers/iio/magnetometer/ak8974.c
@@ -54,15 +54,15 @@
 #define AK8974_DATA_X		0x10
 #define AK8974_DATA_Y		0x12
 #define AK8974_DATA_Z		0x14
-#define AK8974_INT_SRC		0x16
+#define AK8974_INT_SRC		0x16	// NOPE
 #define AK8974_STATUS		0x18
-#define AK8974_INT_CLEAR	0x1A
+#define AK8974_INT_CLEAR	0x1A	// NOPE
 #define AK8974_CTRL1		0x1B
 #define AK8974_CTRL2		0x1C
 #define AK8974_CTRL3		0x1D
-#define AK8974_INT_CTRL		0x1E
+#define AK8974_INT_CTRL		0x1E	// NOPE, CTRL4
 #define AK8974_INT_THRES	0x26  /* Absolute any axis value threshold */
-#define AK8974_PRESET		0x30
+#define AK8974_PRESET		0x30	// NOPE
 
 /* AK8974-specific offsets */
 #define AK8974_OFFSET_X		0x20
@@ -116,14 +116,14 @@
 
 #define AK8974_STATUS_DRDY	BIT(6) /* Data ready */
 #define AK8974_STATUS_OVERRUN	BIT(5) /* Data overrun */
-#define AK8974_STATUS_INT	BIT(4) /* Interrupt occurred */
+#define AK8974_STATUS_INT	BIT(4) /* Interrupt occurred */	// NOPE
 
 #define AK8974_CTRL1_POWER	BIT(7) /* 0 = standby; 1 = active */
-#define AK8974_CTRL1_RATE	BIT(4) /* 0 = 10 Hz; 1 = 20 Hz	 */
+#define AK8974_CTRL1_RATE	BIT(4) /* 0 = 10 Hz; 1 = 20 Hz	 */ // not quite
 #define AK8974_CTRL1_FORCE_EN	BIT(1) /* 0 = normal; 1 = force	 */
-#define AK8974_CTRL1_MODE2	BIT(0) /* 0 */
+#define AK8974_CTRL1_MODE2	BIT(0) /* 0 */ // NOPE
 
-#define AK8974_CTRL2_INT_EN	BIT(4)  /* 1 = enable interrupts	      */
+#define AK8974_CTRL2_INT_EN	BIT(4)  /* 1 = enable interrupts	      */ // NOPE
 #define AK8974_CTRL2_DRDY_EN	BIT(3)  /* 1 = enable data ready signal */
 #define AK8974_CTRL2_DRDY_POL	BIT(2)  /* 1 = data ready active high   */
 #define AK8974_CTRL2_RESDEF	(AK8974_CTRL2_DRDY_POL)
```

We can use the reported `ak8974->variant` to add special handling for some of the registers. I would:

1. Update `ak8974_writeable_reg` to disallow writing to registers that don't exist.

2. `AK8974_INT_SRC` and `AK8974_INT_CLEAR` are only used read-only. Apparently they don't cause any issues, so I guess we could leave the following two reads as-is: (not sure)

    https://github.com/novathor-mainline/linux/blob/5dadd3d12d57562a272b849777b1acaa2cc5d2c0/drivers/iio/magnetometer/ak8974.c#L352-L354

    https://github.com/novathor-mainline/linux/blob/5dadd3d12d57562a272b849777b1acaa2cc5d2c0/drivers/iio/magnetometer/ak8974.c#L284-L287

3. `AK8974_INT_CTRL` actually refers to a different register ("CTRL4"). We shouldn't write the interrupt configuration to it. Looking at [`hscdtd008a_i2c.c` the downstream driver writes 0x90](https://github.com/novathor-mainline/android_kernel/blob/9508895090960012f916561b2ede5eaf8124fabd/drivers/sensor/alps/hscdtd008a_i2c.c#L348-L350).

4. `AK8974_PRESET` is not needed at all, I guess.

5. `AK8974_CTRL1_RATE` has 2 bits instead (more possible values). Not sure if we need to handle it somewhere.

6. `AK8974_CTRL2_INT_EN` means something different (FIFO enable). The downstream driver does not write to CTRL2 at all, so I don't think we want to enable the FIFO.

These are just some thoughts, please let me know if you want to discuss something.

2020-01-25 19:11 UTC, stephan-gh commented on drivers/iio/magnetometer/ak8974.c
> +	case AK8974_WHOAMI_VALUE_HSCDTD008A:
I would move this below `case AK8974_WHOAMI_VALUE_AK8974:`. Then the switch statement is ordered by WHOAMI.

2020-01-25 19:11 UTC, stephan-gh commented on drivers/iio/magnetometer/ak8974.c
> +			return true;
You could combine this with an OR above.

2020-01-27 19:46 UTC, AffeAli commented
I changed the simple stuff.
With the registers I tried tons of different variations (mostly with `AK8974_INT_CTRL` and `AK8974_PRESET`) of (not) writing  to them and nothing worked. At least for now I'm out of ideas on this.

2020-01-28 12:18 UTC, Minecrell commented
@AffeAli Does "nothing worked" mean reading values fails? Initialization fails? What is broken exactly?

2020-01-28 13:29 UTC, AffeAli commented
Sorry about my imprecise answer, I was a bit frustrated. Not writing to `AK8974_INT_CTRL` makes the reset fail. With the following patch (writing 0x90 to `AK8974_INT_CTRL` and not writing to `AK8974_PRESET`) the sensor values seem like they sometimes overflow. (They are near the 16-bit integer max value)
```
diff --git a/drivers/iio/magnetometer/ak8974.c b/drivers/iio/magnetometer/ak8974.c
index e2b31e9d4b35..dbbef8b8a3ef 100644
--- a/drivers/iio/magnetometer/ak8974.c
+++ b/drivers/iio/magnetometer/ak8974.c
@@ -242,10 +242,17 @@ static int ak8974_reset(struct ak8974 *ak8974)
        ret = regmap_write(ak8974->map, AK8974_CTRL3, AK8974_CTRL3_RESDEF);
        if (ret)
                return ret;
-       ret = regmap_write(ak8974->map, AK8974_INT_CTRL,
-                          AK8974_INT_CTRL_RESDEF);
-       if (ret)
-               return ret;
+       if (ak8974->variant != AK8974_WHOAMI_VALUE_HSCDTD008A) {
+               ret = regmap_write(ak8974->map, AK8974_INT_CTRL,
+                                  AK8974_INT_CTRL_RESDEF);
+               if (ret)
+                       return ret;
+       } else {
+               ret = regmap_write(ak8974->map, AK8974_INT_CTRL,
+                                  0x90);
+               if (ret)
+                       return ret;
+       }
 
        /* After reset, power off is default state */
        return ak8974_set_power(ak8974, AK8974_PWR_OFF);
@@ -268,6 +275,9 @@ static int ak8974_configure(struct ak8974 *ak8974)
                if (ret)
                        return ret;
        }
+       if (ak8974->variant == AK8974_WHOAMI_VALUE_HSCDTD008A) {
+               return 0;
+       }
        ret = regmap_write(ak8974->map, AK8974_INT_CTRL, AK8974_INT_CTRL_POL);
        if (ret)
                return ret;
@@ -679,20 +689,18 @@ static bool ak8974_writeable_reg(struct device *dev, unsigned int reg)
        case AK8974_INT_CTRL:
        case AK8974_INT_THRES:
        case AK8974_INT_THRES + 1:
+               return true;
        case AK8974_PRESET:
        case AK8974_PRESET + 1:
-               return true;
+               return ak8974->variant != AK8974_WHOAMI_VALUE_HSCDTD008A;
        case AK8974_OFFSET_X:
        case AK8974_OFFSET_X + 1:
        case AK8974_OFFSET_Y:
```

2020-01-28 18:44 UTC, Minecrell commented
> Sorry about my imprecise answer, I was a bit frustrated. 

I know that feeling :) It happens occasionally when working on kernel development, I don't think there is any way to avoid it. :/

> Not writing to AK8974_INT_CTRL makes the reset fail. With the following patch (writing 0x90 to AK8974_INT_CTRL and not writing to AK8974_PRESET) the sensor values seem like they sometimes overflow. (They are near the 16-bit integer max value)

Curious, does it really behave differently than before? I thought I saw negative values returned by  `in_magn_*_raw`, but I re-tested without your last changes and still get the 65000+ numbers.

2020-01-28 19:08 UTC, AffeAli commented
I just tested my changes again and I never got any negative values. 65000+ are common with the patch in my comment, but with the code in the PR only when holding a magnet close to the phone. Without a magnet it is always within ~5-500.

2020-01-28 19:31 UTC, stephan-gh commented
@AffeAli Thanks for testing! The following change should fix negative values I think:

```diff
diff --git a/drivers/iio/magnetometer/ak8974.c b/drivers/iio/magnetometer/ak8974.c
index e2b31e9d4b35..d380c3e9423b 100644
--- a/drivers/iio/magnetometer/ak8974.c
+++ b/drivers/iio/magnetometer/ak8974.c
@@ -569,7 +569,7 @@ static int ak8974_read_raw(struct iio_dev *indio_dev,
 		 * We read all axes and discard all but one, for optimized
 		 * reading, use the triggered buffer.
 		 */
-		*val = le16_to_cpu(hw_values[chan->address]);
+		*val = (s16) le16_to_cpu(hw_values[chan->address]);
 
 		ret = IIO_VAL_INT;
 	}
```

It happens because the raw value is not actually interpreted as signed integer. With this change, I don't get anything close to 65000, because these are actually negative numbers.

If you re-test with and without writing 0x90 to AK8974_INT_CTRL (aka CTRL4) the difference should be more minimal now.

On normal AK8974, the output is always a signed 16-bit number. On HSCDTD008A the output is capped to 14-bit (-8192 to 8191) by default. By writing `0x90` to CTRL4 we change it to output signed 15-bit numbers (-16384 to 16383) instead. Therefore the values should be approx. twice as large in the same situation.

2020-02-12 19:08 UTC, stephan-gh requested changes

2020-02-12 19:08 UTC, stephan-gh commented on drivers/iio/magnetometer/ak8974.c
> +				   0x90);
To make this less confusing it might help if you create extra constants for these two:

e.g.

```diff
diff --git a/drivers/iio/magnetometer/ak8974.c b/drivers/iio/magnetometer/ak8974.c
index e2b31e9d4b35..9d07605ba623 100644
--- a/drivers/iio/magnetometer/ak8974.c
+++ b/drivers/iio/magnetometer/ak8974.c
@@ -141,6 +141,12 @@
 #define AK8974_INT_CTRL_PULSE	BIT(1) /* 0 = latched; 1 = pulse (50 usec) */
 #define AK8974_INT_CTRL_RESDEF	(AK8974_INT_CTRL_XYZEN | AK8974_INT_CTRL_POL)
 
+/* HSCDTD008A-specific control register */
+#define HSCDTD008A_CTRL4	0x1E
+#define HSCDTD008A_CTRL4_MMD	BIT(7)	/* must be set to 1 */
+#define HSCDTD008A_CTRL4_RANGE	BIT(4)	/* 0 = 14-bit output; 1 = 15-bit output */
+#define HSCDTD008A_CTRL4_RESDEF	(HSCDTD008A_CTRL4_MMD | HSCDTD008A_CTRL4_RANGE)
+
 /* The AMI305 has elaborate FW version and serial number registers */
 #define AMI305_VER		0xE8
 #define AMI305_SN		0xEA
```

then use `HSCDTD008A_CTRL4` and `HSCDTD008A_CTRL4_RESDEF` (= 0x90) in this function call.

2020-02-12 19:08 UTC, stephan-gh commented on drivers/iio/magnetometer/ak8974.c
> +	}
no need for brackets here

2020-02-12 19:08 UTC, stephan-gh commented on arch/arm/boot/dts/ste-ux500-samsung-golden.dts
> +			avdd-supply = <&ab8500_ldo_aux8_reg>;
Check the schematics to see which regulator belongs to which supply :)

2020-02-13 17:11 UTC, AffeAli commented on arch/arm/boot/dts/ste-ux500-samsung-golden.dts
> +			avdd-supply = <&ab8500_ldo_aux8_reg>;
I was convinced I had them right this time :(

2020-02-13 17:12 UTC, AffeAli commented
Should I split your cast-to-s16 fix into a separate commit, as it is relevant for the entire driver?

2020-02-13 18:06 UTC, Minecrell commented
> Should I split your cast-to-s16 fix into a separate commit, as it is relevant for the entire driver?

I was going to send that upstream separately very soon(TM).

2020-02-13 20:30 UTC, stephan-gh approved these changes

2020-02-14 11:14 UTC, merged

2020-02-14 11:15 UTC, Minecrell commented
Tested on my samsung-golden. Seems to work fine.

I made a separate patch for the `(s16)` fix and sent it upstream. Should get applied in a couple of days. Then you can send your patches on top of it :)

Thanks again!